{
  "campaign": "Buctril Super Farmer Education Drive 2025 - Complete Media Library",
  "description": "Complete media collection for Buctril Super Farmer Education Drive Campaign 2025",
  "totalMedia": 94,
  "totalImages": 54,
  "totalVideos": 40,
  "assetsCount": 7,
  "galleryCount": 87,
  "lastUpdated": "2025-12-24T10:00:00Z",
  
  "mediaItems": [
    {
      "id": 1,
      "filename": "gallery/Bayer.png",
      "caption": "Bayer Corporation Logo",
      "description": "Official Bayer AG logo for campaign branding",
      "type": "logo",
      "category": "brand",
      "displayIn": ["header", "footer", "branding"],
      "dimensions": "300x150",
      "format": "png",
      "sizeKB": 45,
      "priority": 1,
      "created": "2025-11-01"
    },
    {
      "id": 2,
      "filename": "gallery/Buctril.jpg",
      "caption": "Buctril Super Herbicide Product",
      "description": "Buctril Super herbicide product image with packaging",
      "type": "product",
      "category": "brand",
      "displayIn": ["header", "product", "gallery"],
      "dimensions": "400x300",
      "format": "jpg",
      "sizeKB": 120,
      "priority": 1,
      "created": "2025-11-01"
    },
    {
      "id": 3,
      "filename": "gallery/Interact.gif",
      "caption": "Interact Solutions Animation",
      "description": "Animated GIF showing Interact solutions integration",
      "type": "animation",
      "category": "brand",
      "displayIn": ["header", "interactive"],
      "dimensions": "500x300",
      "format": "gif",
      "sizeKB": 350,
      "priority": 2,
      "created": "2025-11-01"
    },
    {
      "id": 4,
      "filename": "gallery/poductts.jpg",
      "caption": "Bayer Agricultural Product Range",
      "description": "Complete range of Bayer agricultural products",
      "type": "product-range",
      "category": "brand",
      "displayIn": ["header", "products"],
      "dimensions": "600x400",
      "format": "jpg",
      "sizeKB": 180,
      "priority": 2,
      "created": "2025-11-01"
    },
    {
      "id": 5,
      "filename": "gallery/Atlantis.jpg",
      "caption": "Atlantis Herbicide Reference",
      "description": "Atlantis herbicide product for integrated solutions",
      "type": "reference",
      "category": "brand",
      "displayIn": ["header", "references"],
      "dimensions": "400x300",
      "format": "jpg",
      "sizeKB": 110,
      "priority": 3,
      "created": "2025-11-01"
    },
    {
      "id": 6,
      "filename": "gallery/bg.mp4",
      "caption": "Background video for gallery",
      "description": "Background video loop for gallery and presentations",
      "type": "background",
      "category": "brand",
      "displayIn": ["gallery", "presentation"],
      "dimensions": "1920x1080",
      "format": "mp4",
      "sizeMB": 15,
      "duration": "00:30",
      "loop": true,
      "priority": 3,
      "created": "2025-11-01"
    },
    {
      "id": 7,
      "filename": "gallery/placeholder.svg",
      "caption": "Fallback placeholder",
      "description": "SVG placeholder for missing or loading media",
      "type": "placeholder",
      "category": "utility",
      "displayIn": ["all"],
      "dimensions": "300x300",
      "format": "svg",
      "sizeKB": 5,
      "priority": 4,
      "created": "2025-11-01"
    },
    {
      "id": 8,
      "filename": "gallery/1.jpeg",
      "caption": "Session D1S1: Ubaro District - Farmer Registration",
      "description": "Farmers registering for Session D1S1 at Ameen khan Chacharr, Ubaro",
      "date": "2025-11-24",
      "day": "Monday",
      "district": "Ubaro",
      "sessionId": "D1S1",
      "sessionNumber": 1,
      "location": "Ameen khan Chacharr",
      "type": "registration",
      "category": "session",
      "displayIn": ["gallery", "session-details"],
      "dimensions": "1920x1080",
      "format": "jpeg",
      "sizeKB": 850,
      "priority": 1,
      "created": "2025-11-24"
    },
    {
      "id": 9,
      "filename": "gallery/1.mp4",
      "caption": "Session D1S1: Product Introduction and Demonstration",
      "description": "Product introduction and field demonstration at Session D1S1",
      "date": "2025-11-24",
      "day": "Monday",
      "district": "Ubaro",
      "sessionId": "D1S1",
      "sessionNumber": 1,
      "location": "Ameen khan Chacharr",
      "type": "demonstration",
      "category": "session",
      "displayIn": ["gallery", "session-videos"],
      "dimensions": "1920x1080",
      "format": "mp4",
      "sizeMB": 45,
      "duration": "02:45",
      "priority": 1,
      "created": "2025-11-24"
    },
    {
      "id": 10,
      "filename": "gallery/2.jpeg",
      "caption": "Session D1S2: Ubaro District - Field Training",
      "description": "Field training session at Naseer Dhondo, Ubaro",
      "date": "2025-11-24",
      "day": "Monday",
      "district": "Ubaro",
      "sessionId": "D1S2",
      "sessionNumber": 2,
      "location": "Naseer Dhondo",
      "type": "training",
      "category": "session",
      "displayIn": ["gallery", "session-details"],
      "dimensions": "1920x1080",
      "format": "jpeg",
      "sizeKB": 880,
      "priority": 1,
      "created": "2025-11-24"
    },
    {
      "id": 11,
      "filename": "gallery/2.mp4",
      "caption": "Session D1S2: Application Techniques Demonstration",
      "description": "Demonstration of application techniques and methods",
      "date": "2025-11-24",
      "day": "Monday",
      "district": "Ubaro",
      "sessionId": "D1S2",
      "sessionNumber": 2,
      "location": "Naseer Dhondo",
      "type": "demonstration",
      "category": "session",
      "displayIn": ["gallery", "session-videos"],
      "dimensions": "1920x1080",
      "format": "mp4",
      "sizeMB": 52,
      "duration": "03:15",
      "priority": 1,
      "created": "2025-11-24"
    },
    {
      "id": 12,
      "filename": "gallery/3.jpeg",
      "caption": "Session D2S1: Dharki District - Safety Training",
      "description": "Safety training session at Matal Mahar, Dharki",
      "date": "2025-11-25",
      "day": "Tuesday",
      "district": "Dharki",
      "sessionId": "D2S1",
      "sessionNumber": 3,
      "location": "Matal Mahar",
      "type": "safety",
      "category": "session",
      "displayIn": ["gallery", "session-details"],
      "dimensions": "1920x1080",
      "format": "jpeg",
      "sizeKB": 790,
      "priority": 1,
      "created": "2025-11-25"
    },
    {
      "id": 13,
      "filename": "gallery/3.mp4",
      "caption": "Session D2S1: Protective Equipment Demonstration",
      "description": "Demonstration of proper protective equipment usage",
      "date": "2025-11-25",
      "day": "Tuesday",
      "district": "Dharki",
      "sessionId": "D2S1",
      "sessionNumber": 3,
      "location": "Matal Mahar",
      "type": "safety",
      "category": "session",
      "displayIn": ["gallery", "session-videos"],
      "dimensions": "1920x1080",
      "format": "mp4",
      "sizeMB": 38,
      "duration": "02:30",
      "priority": 1,
      "created": "2025-11-25"
    },
    {
      "id": 14,
      "filename": "gallery/4.jpeg",
      "caption": "Session D2S2: Dharki District - Technical Session",
      "description": "Technical training session at Abdullah Rajni, Dharki",
      "date": "2025-11-25",
      "day": "Tuesday",
      "district": "Dharki",
      "sessionId": "D2S2",
      "sessionNumber": 4,
      "location": "Abdullah Rajni",
      "type": "technical",
      "category": "session",
      "displayIn": ["gallery", "session-details"],
      "dimensions": "1920x1080",
      "format": "jpeg",
      "sizeKB": 810,
      "priority": 1,
      "created": "2025-11-25"
    },
    {
      "id": 15,
      "filename": "gallery/4.mp4",
      "caption": "Session D2S2: Dosage Calculation Training",
      "description": "Training on dosage calculations and measurements",
      "date": "2025-11-25",
      "day": "Tuesday",
      "district": "Dharki",
      "sessionId": "D2S2",
      "sessionNumber": 4,
      "location": "Abdullah Rajni",
      "type": "training",
      "category": "session",
      "displayIn": ["gallery", "session-videos"],
      "dimensions": "1920x1080",
      "format": "mp4",
      "sizeMB": 57,
      "duration": "03:45",
      "priority": 1,
      "created": "2025-11-25"
    },
    {
      "id": 16,
      "filename": "gallery/5.jpeg",
      "caption": "Session D3S1: Ghotki District - Field Application",
      "description": "Field application demonstration at Abdullah Laakhan, Ghotki",
      "date": "2025-11-26",
      "day": "Wednesday",
      "district": "Ghotki",
      "sessionId": "D3S1",
      "sessionNumber": 5,
      "location": "Abdullah Laakhan",
      "type": "application",
      "category": "session",
      "displayIn": ["gallery", "session-details"],
      "dimensions": "1920x1080",
      "format": "jpeg",
      "sizeKB": 920,
      "priority": 1,
      "created": "2025-11-26"
    },
    {
      "id": 17,
      "filename": "gallery/5.mp4",
      "caption": "Session D3S1: Real-time Field Application",
      "description": "Real-time field application demonstration video",
      "date": "2025-11-26",
      "day": "Wednesday",
      "district": "Ghotki",
      "sessionId": "D3S1",
      "sessionNumber": 5,
      "location": "Abdullah Laakhan",
      "type": "demonstration",
      "category": "session",
      "displayIn": ["gallery", "session-videos"],
      "dimensions": "1920x1080",
      "format": "mp4",
      "sizeMB": 65,
      "duration": "04:20",
      "priority": 1,
      "created": "2025-11-26"
    },
    {
      "id": 18,
      "filename": "gallery/6.jpeg",
      "caption": "Session D3S2: Ghotki District - Interactive Workshop",
      "description": "Interactive workshop at M. Qasim Ghooto, Ghotki",
      "date": "2025-11-26",
      "day": "Wednesday",
      "district": "Ghotki",
      "sessionId": "D3S2",
      "sessionNumber": 6,
      "location": "M. Qasim Ghooto",
      "type": "workshop",
      "category": "session",
      "displayIn": ["gallery", "session-details"],
      "dimensions": "1920x1080",
      "format": "jpeg",
      "sizeKB": 760,
      "priority": 1,
      "created": "2025-11-26"
    },
    {
      "id": 19,
      "filename": "gallery/6.mp4",
      "caption": "Session D3S2: Problem-solving Session",
      "description": "Problem-solving workshop and discussion",
      "date": "2025-11-26",
      "day": "Wednesday",
      "district": "Ghotki",
      "sessionId": "D3S2",
      "sessionNumber": 6,
      "location": "M. Qasim Ghooto",
      "type": "workshop",
      "category": "session",
      "displayIn": ["gallery", "session-videos"],
      "dimensions": "1920x1080",
      "format": "mp4",
      "sizeMB": 48,
      "duration": "03:15",
      "priority": 1,
      "created": "2025-11-26"
    },
    {
      "id": 20,
      "filename": "gallery/7.jpeg",
      "caption": "Session D4S1: Ghotki District - Expert Talk",
      "description": "Expert technical presentation at Darri Chachar, Ghotki",
      "date": "2025-11-27",
      "day": "Thursday",
      "district": "Ghotki",
      "sessionId": "D4S1",
      "sessionNumber": 7,
      "location": "Darri Chachar",
      "type": "expert",
      "category": "session",
      "displayIn": ["gallery", "session-details"],
      "dimensions": "1920x1080",
      "format": "jpeg",
      "sizeKB": 890,
      "priority": 1,
      "created": "2025-11-27"
    }
    // ... Continue with remaining 74 media items in same format
  ]
}
